/**
 * @file     EXTERN_MACRO_C2000.h
 * @author   
 * @date     2022-08-01 15:02:41
 */ 
/****************************************************************************************************************************************************\
***
 *** ATTENTION! - This file is a STUB CODE FILE. It is NOT a PRODUCTION CODE FILE.
 ***
 *** Stub code files are auxiliary files generated by TargetLink and ONLY intended to allow
 *** SIMULATION of code generation units without building the overall application. Stub code
 *** files in general are NOT COMPLETE in comparison to the corresponding production code files.
 *** Therefore, to be fully functional, a production code application MUST NOT contain any stub
 *** code files at all.
 ***
 \****************************************************************************************************************************************************/

#ifndef EXTERN_MACRO_C2000_H
#define EXTERN_MACRO_C2000_H

/*--------------------------------------------------------------------------------------------------------------------------------------------------*\
  DEFINES (OPT)
 \*--------------------------------------------------------------------------------------------------------------------------------------------------*/
/*--------------------------------------------------------------------------------------------------------------------------------------------------*\
  INCLUDES
 \*--------------------------------------------------------------------------------------------------------------------------------------------------*/
#include "MacroDefine.h"
#include "TypeDefine.h"
//#include "Source/CommunicationModule/Comm/COM/COM_CommDef.h"

/*--------------------------------------------------------------------------------------------------------------------------------------------------*\
  ENUMS
 \*--------------------------------------------------------------------------------------------------------------------------------------------------*/

typedef enum tagAvr_Selection
{
	AVR_CONST_MODE = 0, /* Description: AVR constant reference voltage mode. The regulation will decouple with instantaneous dc-bus voltage. */
	AVR_LPF_MODE = 1, /* Description: AVR LPF reference voltage mode. The regulation will use dc-bus voltage which is low-pass filtered. */
	AVR_INST_MODE = 2 /* Description: AVR INST reference voltage mode. The regulation will use instantaneous dc-bus voltage. */
} emAVR_SELECTION; /* Description: Automatic Voltage Regulation method selection */

typedef enum tagDaxis_Cur_Ctrl
{
	NORMAL_FLUXWKN = 0, /* Description: D-axis current reference with normal wlux weakening process. */
	EXP_CUR_SPM = 1, /* Description: D-axis current reference with positive exponential-decay offset. */
	EXP_CUR_IPM = 2, /* Description: D-axis current reference with negtive exponential-decay offset. */
	DIRECT_CUR_REF = 3, /* Description: D-axis current reference assigned by external command. */
	FLUXWKN_INDUCT_EST = 4, /* Description: Flux weakening function use online inductor estimation result. */
	MTPV_SPM = 8, /* Description: MTPVunder SPM mode. */
	MTPV_ENABLE = 16, /* Description: MTPV enable. */
	MTPV_INDUCT_EST = 32, /* Description: MTPV function use online inductor estimation result. */
	MTPA_ENABLE = 64, /* Description: MTPA enable. */
	MTPA_INDUCT_EST = 128 /* Description: MTPA function use online inductor estimation result. */
} emDAXIS_CUR_CTRL; /* Description: Daxis current reference bitfield control flags. */

typedef enum tagDaxis_Cur_Status
{
	FLUX_WKN_OP = 0, /* Description: Motor under flux-weakening operation */
	MTPA_OP = 1, /* Description: Motor under maximum-torque-per-ampere operation */
	MTPV_OP = 2, /* Description: Motor under maximum-torque-per-voltage operation */
	EXT_REF_OP = 3 /* Description: Motor operated under external d-axis current reference. */
} emDAXIS_CUR_STATUS; /* Description: SM d-axis current reference status definition */

typedef enum tagDbc_Selection
{
	DBC_INST_TRAPZ = 0, /* Description: Trapezoidal curve based dead-time compensation which calculated by current magnitude. */
	DBC_ANGLE_TRAPZ = 1, /* Description: Trapezoidal curve based dead-time compensation which calculated by current angle. */
	DBC_INST_ARCTAN = 2, /* Description: Arctan curve based dead-time compensation. */
	DBC_INST_LUT = 3, /* Description: LUT-based dead-time compensation. */
	DBC_DISABLE = 4 /* Description: Disable compensation. */
} emDBC_SELECTION; /* Description: Dead-time compensation method selection */

typedef enum tagInertia_Est
{
	INERTIA_INIT_SET = 1, INERTIA_INIT_ACC = 2, INERTIA_GET_TORQ = 3, INERTIA_SECOND_ACC = 4, INERTIA_EST_END = 5, INERTIA_EST_FAIL = 6
} emINERTIA_EST; /* Description: Inertia estimation step enumeration */

/*Defined In TypeDefine.h*/
//typedef enum tagMotor_Type
//{
//	IM = 0, SPM = 1, IPM = 2, SYNRM = 3
//} emMOTOR_TYPE; /* Description: Motor type. */

typedef enum tagSlsm_Ctrl_Status
{
	PG_MODE = 0, /* Description: FOC control with external position and speed feedback. This mode SHOULD NOT switch to HFI mode. */
	IF_MODE = 1, /* Description: Constant current control mode. This mode SHOULD NOT switch to HFI mode. */
	HFI_MODE = 2, /* Description: FOC control with high frequency injection based speed and position estimator. */
	FOB_MODE = 3, /* Description: FOC control with flux observer based speed and position estimator. */
	FOB_MODE_HFINJ = 4 /* Description: FOC control with flux observer based speed and position estimator. And injecting high frequency to get ready to
	 enter HFI mode. */
} emSLSM_CTRL_STATUS; /* Description: Synchronous motor FOC sensorlesss control mode status */

typedef enum tagVf_Curve
{
	POLYLINE_TRIPLE = 0, LINEAR_1P5TH = 1, LINEAR_2ND = 2, LINEAR_1ST = 3, POLYLINE_BOOSTED = 4
} emVF_CURVE; /* Description: VF table curve type. */

/*--------------------------------------------------------------------------------------------------------------------------------------------------*\
  DEFINES
 \*--------------------------------------------------------------------------------------------------------------------------------------------------*/

#define DB_TO_POWER_CONST ((Float32) -0.05F) /* Description: Constant of transforming dB value to power value  */
#define FLOAT_DEG_TO_RAD ((Float32) 0.01745329252F) /* Description: PI/180 in single precision floating point */
#define FLOAT_FIVE ((Float32) 5.F) /* Description: Numerical constant 5. */
#define FLOAT_FORTY ((Float32) 40.F) /* Description: Numerical constant 40. */
#define FLOAT_HUNDRED_FORTY_FIVE ((Float32) 145.F) /* Description: Numerical constant 145. */
#define FLOAT_MINUS_POINT_ONE ((Float32) -0.1F) /* Description: Numerical constant 0.1. */
#define FLOAT_NINE ((Float32) 9.F) /* Description: Numerical constant 9. */
#define FLOAT_ONE_HUNDRED ((Float32) 100.F) /* Description: Numerical constant 100. */
#define FLOAT_ONE_POINT_FIVE ((Float32) 1.5F) /* Description: Numerical constant 1.5. */
#define FLOAT_ONE_THOUSAND ((Float32) 1000.F) /* Description: Numerical constant 1000. */
#define FLOAT_POINT_ZERO_ONE ((Float32) 0.01F) /* Description: Numerical constant 0.01. */
#define FLOAT_QUARTER ((Float32) 0.25F) /* Description: Numerical contstant 0.25. */
#define FLOAT_RAD_TO_DEG ((Float32) 57.29577951F) /* Description: 180/PI in single precision floating point */
#define FLOAT_SEVEN ((Float32) 7.F) /* Description: Numerical constant 7. */
#define FLOAT_SIX ((Float32) 6.F) /* Description: Numerical constant 6. */
#define FLOAT_SIXTEEN ((Float32) 16.F) /* Description: Floating point 16 for QAC used. */
#define FLOAT_TWENTY_FIVE ((Float32) 25.F) /* Description: Numerical constant 25. */
#define FLOAT_TWO_HUNDRED_EIGHTY ((Float32) 280.F) /* Description: Numerical constant 280. */
#define GAIN_ENABLE_BOUND_RESD1 ((Float32) 0.1F) /* Description: Function enable/disable switching boundary. By checking the minimum resolution of floating point gain which being compared with, you can choose suitable macro to use. */
#define GAIN_ENABLE_BOUND_RESD3 ((Float32) 0.001F) /* Description: Function enable/disable switching boundary. By checking the minimum resolution of floating point gain which being compared with, you can choose suitable macro to use. */
#define HALF_PI ((Float32) 1.570796327F) /* Description: half pi in single precision  floating point */
#define INT_100US ((Float32) 0.0001F) /* Description: interrupt timer for 100us in [sec] */
#define INT_500US ((Float32) 0.0005F) /* Description: interrupt time for 500us in [sec] */
#define INV_PI ((Float32) 0.318309886F) /* Description: Inverse pi in single precision  floating point */
#define NEG_PI ((Float32) -3.141592653F) /* Description: -pi in single precision floating point */
#define NEG_TWO_PI ((Float32) -6.28318531F) /* Description: -2*pi in single precision floating point */
#define SQRT_2DIV3 ((Float32) 0.81649658F) /* Description: sqrt(2/3) in single precision floating point. */
#define SQRT_3DIV2 ((Float32) 1.2247449F) /* Description: sqrt(3/2) in single precision floating point. */
#define SQRT_3DIV4 ((Float32) 0.8660254F) /* Description: sqrt(3/4) in single precision floating point. */
#define THREE_DIV_FOUR ((Float32) 0.75F) /* Description: numerical constant for 3/4 */
#define TWO_DIV_THREE_PI ((Float32) 2.094395102F) /* Description: 2/3*pi in single precision floating point */
#define ULONG_ONE ((ULONG) 1) /* Description: Numerical constant 1. */
#define ULONG_ZERO ((ULONG) 0) /* Description: Numerical constant 0. */
#define FLOAT_EIGHT ((Float32) 8.F) /* Description: Numerical constant 8. */
#define FLOAT_FOUR ((Float32) 4.F) /* Description: Numerical constant 4. */
#define FLOAT_FOUR_POINT_SIX ((Float32) 4.6F) /* Description: Numerical constant 4.6. */
#define FLOAT_HALF ((Float32) 0.5F) /* Description: Numerical contstant 0.5. */
#define FLOAT_INV_THREE ((Float32) 0.333333333F) /* Description: Numerical constant 1/3. */
#define FLOAT_MINUS_ONE ((Float32) -1.F) /* Description: Numerical constant -1. */
#define FLOAT_ONE ((Float32) 1.F) /* Description: Numerical constant 1. */
#define FLOAT_POINT_ONE ((Float32) 0.1F) /* Description: Numerical constant 0.1. */
#define FLOAT_TEN ((Float32) 10.F) /* Description: Numerical constant 10. */
#define FLOAT_THREE ((Float32) 3.F) /* Description: Numerical constant 3. */
#define FLOAT_TWENTY ((Float32) 20.F) /* Description: Numerical constant 20. */
#define FLOAT_TWO ((Float32) 2.F) /* Description: Numerical constant 2. */
#define FLOAT_ZERO ((Float32) 0.F) /* Description: Floating point zero for QAC used. */
#define GAIN_ENABLE_BOUND_RESD2 ((Float32) 0.01F) /* Description: Function enable/disable switching boundary. By checking the minimum resolution of floating point gain which being compared with, you can choose suitable macro to use. */
#define GAIN_ENABLE_BOUND_RESD4 ((Float32) 0.0001F) /* Description: Function enable/disable switching boundary. By checking the minimum resolution of floating point gain which being compared with, you can choose suitable macro to use. */
#define INT_1MS ((Float32) 0.001F) /* Description: interrupt time for 1ms in [sec] */
#define INVT_MAX_CUR_COEF ((Float32) 2.5F) /* Description: Maximum current coeficient to inverter rated current. */
#define INV_SQRT2 ((Float32) 0.70710678F) /* Description: 1/sqrt(2) in single precision floating point. */
#define INV_SQRT3 ((Float32) 0.57735027F) /* Description: 1/sqrt(3) in single precision floating point. */
#define INV_TWO_PI ((Float32) 0.159154943F) /* Description: Inverse 2*pi in single precision floating point */
#define MIN_FREQ_CMD ((Float32) 0.01F) /* Description: Minimum frequency command Step. */
#define PCT_UNIT ((Float32) 0.01F) /* Description: Percentage unit value. */
#define PI ((Float32) 3.141592653F) /* Description: pi in single precision  floating point */
#define SQRT_2 ((Float32) 1.41421356F) /* Description: sqrt(2) in single precision floating point */
#define SQRT_3 ((Float32) 1.73205081F) /* Description: sqrt(3) in single precision floating point. */
#define THREE_DIV_TWO ((Float32) 1.5F) /* Description: numerical constant for 3/2 */
#define TWO_PI ((Float32) 6.28318531F) /* Description: 2*pi in single precision floating point */

#define ABS_P2P ((UWORD) 4096) /* Description: Absolute point to point control operation mode */
#define ACR_TQCPG ((UWORD) 1024) /* Description: Current control in TQC PG operation mode */
#define ASR_FOCPG ((UWORD) 512) /* Description: Speed control in FOC PG operation mode */
#define CM_ABS_APRIM ((UWORD) 4773) /* Description: ABS_APRIM(Absolute point control): no VF, with PG, Speed control, point 2 point control, IM, with ASR, No ACR, Absolute point, No Homing, No Sensorless (CTRLM =5) */
#define CM_ABS_APRPM ((UWORD) 5029)
#define CM_FOCIM ((UWORD) 16387) /* Description: FOCIM Control Mode, no VF, no PG, Speed control, IM, No ASR, No ACR, Relative point, No Homing, Sensorless (CTRLM =3) */
#define CM_FOCPGIM ((UWORD) 548) /* Description: FOCPGIM Control Mode: no VF, with PG, Speed control, IM, with ASR, No ACR, Relative point, No Homing, No Sensorless (CTRLM =4) */
#define CM_FOCPGPM ((UWORD) 804)
#define CM_FOCPM ((UWORD) 16643)
#define CM_REL_APRIM ((UWORD) 677) /* Description: REL_APRIM(Relative point control): no VF, with PG, Speed control, point 2 point control, IM, with ASR, No ACR, Relative point, No Homing, No Sensorless (CTRLM =5) */
#define CM_REL_APRPM ((UWORD) 933)
#define CM_REL_HOMIM ((UWORD) 8872)
#define CM_REL_HOMPM ((UWORD) 9128)
#define CM_SVC ((UWORD) 17) /* Description: SVC Control Mode, VF, no PG, Speed control, IM, No ASR, No ACR, Relative point, No Homing, No Sensorless (CTRLM =1) */
#define CM_TQCIM ((UWORD) 16454) /* Description: TQCIM(IM torque control): no VF, no PG, Speed control, No point 2 point control, IM, no ASR, No ACR, Relative point, No Homing, Sensorless (CTRLM =6) */
#define CM_TQCPGIM ((UWORD) 1127) /* Description: TQCPGIM(IM torque control with PG): no VF, with PG, Speed control, No point 2 point control, IM, no ASR, with ACR, Relative point, No Homing, No Sensorless (CTRLM =7) */
#define CM_TQCPGPM ((UWORD) 1383)
#define CM_TQCPM ((UWORD) 326)
#define CM_VF ((UWORD) 16) /* Description: VF Control Mode, no PG, Speed control, IM, No ASR, No ACR, Relative point, No Homing, No Sensorless (CTRLM = 0) */
#define CM_VFPG ((UWORD) 50) /* Description: VFPG Control Mode: VF, with PG, Speed control, IM, No ASR, No ACR, Relative point, No Homing, No Sensorless (CTRLM =2) */
#define COUNT_TRIRTY_SECOND_IN_1MS ((UWORD) 30000) /* Description: Counter value in 1ms-function when 5 second. */
#define FOC_SENSORLESS ((UWORD) 16384) /* Description: FOC sensorless operation mode */
#define HOMING_MODE ((UWORD) 8192) /* Description: Homing mode operation mode */
#define P2P_MODE ((UWORD) 128) /* Description: Point to Point operation mode */
#define PM_MOTOR ((UWORD) 256) /* Description: PM motor operation mode */
#define TQC_MODE ((UWORD) 64) /* Description: Torque control operation mode */
#define UWORD_ONE ((UWORD) 1) /* Description: Numerical constant 1. */
#define UWORD_THREE ((UWORD) 3) /* Description: Numerical constant 3. */
#define UWORD_TWO ((UWORD) 2) /* Description: Numerical constant 2. */
#define UWORD_ZERO ((UWORD) 0) /* Description: Numerical constant 0. */
#define VF_MODE ((UWORD) 16) /* Description: VF operation mode */
#define WITH_PG ((UWORD) 32) /* Description: PG operation mode */

#define ACCON ((Bool) 1) /* Description: acceleration condition */
#define AUTO_CT_GAIN ((UBYTE) 10) /* Description: Gain of Current Sensor Calibration Testing */
#define AUTO_CURCALIB ((UBYTE) 11) /* Description: New Current Gain Calibration */
#define AUTO_DBCSECA ((UBYTE) 7) /* Description: Dead Band Compensation SElf CAlibration testing */
#define AUTO_HFSS ((UBYTE) 2) /* Description: High Frequency Lock testing */
#define AUTO_IM_FLXCRV ((UBYTE) 6) /* Description: IM flux curve testing */
#define AUTO_IM_STANDSTILL ((UBYTE) 8) /* Description: Standstill auto tuning testing for IM */
#define AUTO_JM_ESTM ((UBYTE) 12) /* Description: Jm Estimation in sensorless FOC */
#define AUTO_LFSL ((UBYTE) 3) /* Description: Mechanical Shaft Lock low Frequency testing */
#define AUTO_PM_HFSS ((UBYTE) 13) /* Description: HFSS tuning of PM motor to get Rs&Ld&Lq */
#define AUTO_PM_MAG_ANG ((UBYTE) 4) /* Description: PM magnetic angle testing */
#define AUTO_PM_PR ((UBYTE) 5) /* Description: PM parameter testing */
#define AUTO_PM_STANDSTILL ((UBYTE) 9) /* Description: Standstill auto tuning testing for PM  */
#define AUTO_PM_ZTHETA ((UBYTE) 14) /* Description: PM Z-pulse electric angle tuning for ABZ type encoder */
#define AUTO_ROTARY ((UBYTE) 1) /* Description: Rotary Testing */
#define BRAKE ((Bool) 0)
#define DECON ((Bool) 0) /* Description: deceleration condition */
#define DQAXIS_VOLT_SEPARATE ((UBYTE) 2) /* Description: Output voltage limitation method under FOC mode. D-axis and q-axis voltage separate limit. */
#define END ((Bool) 1) /* Description: end condition */
#define ERR ((Bool) 0) /* Description: error condition */
//#define FALSE ((Bool) 0) /* Defined in MacroDefine.h */
#define HI ((Bool) 1)
#define LO ((Bool) 0)
#define MOT_TYPE_IM ((UBYTE) 0) /* Description: Induction motor macro for identification or mode switching. */
#define MOT_TYPE_SPM ((UBYTE) 1) /* Description: Surface mounted permanent motor macro for identification or mode switching. */
#define NEG_TORQ_LIMIT ((UBYTE) 8) /* Description: Analog input seletion for negtive torque limit. */
#define POSNEG_TORQ_LIMIT ((UBYTE) 10) /* Description: Analog input seletion for positive and negtive torque limit. */
#define POS_TORQ_LIMIT ((UBYTE) 7) /* Description: Analog input seletion for positive torque limit. */
#define REG_TORQ_LIMIT ((UBYTE) 9) /* Description: Analog input seletion for regenerative torque limit. */
#define RELEASE ((Bool) 1)
#define RUN ((Bool) 1)
#define SEL_ACR_MODE ((Bool) 0) /* Description: Select ACR control mode of FOCSLIM. */
#define SEL_VFF_MODE ((Bool) 1) /* Description: Select VFF control mode of FOCSLIM. */
#define STOP ((Bool) 0)
#define UBYTE_THREE ((UBYTE) 3) /* Description: Numerical constant 3. */
#define UBYTE_TWO ((UBYTE) 2) /* Description: Numerical constant 2. */
#define BELOW_LOW_LIM ((UBYTE) 2) /* Description: Input is below lower limit. */
#define CLR ((Bool) 0) /* Defined in COM_CommDef.h */
#define DAXIS_VOLT_PRIO_FIRST ((UBYTE) 0) /* Description: Output voltage limitation method under FOC mode. D-axis voltage have higher control priority. */
#define FORWARD ((Bool) 0)
#define MIN_VOLT_PHASE_ERROR ((UBYTE) 1) /* Description: Output voltage limitation method under FOC mode. Make output voltage have minimum phase error. */
#define MOT_MODE ((Bool) 0)
#define MOT_TYPE_IPM ((UBYTE) 2) /* Description: Interior mounted permanent motor macro for identification or mode switching. */
#define MOT_TYPE_SYNRM ((UBYTE) 3) /* Description: Synchronous reluctance motor macro for identification or mode switching. */
#define NORMAL ((UBYTE) 0) /* Description: Normal state, no saturation occurs. */
#define OFF ((Bool) 0) /* Defined in COM_CommDef.h */
#define ON ((Bool) 1)  /* Defined in COM_CommDef.h */
#define OVER_UP_LIM ((UBYTE) 1) /* Description: Input is over upper limit. */
#define REG_MODE ((Bool) 1)
#define REVERSE ((Bool) 1)
#define SET ((Bool) 1) /* Defined in COM_CommDef.h */
#define SPD_MODE ((Bool) 0)
#define TORQ_MODE ((Bool) 1)
//#define TRUE ((Bool) 1) /* Defined in MacroDefine.h */
#define UBYTE_ONE ((UBYTE) 1) /* Description: Numerical constant 1. */
#define UBYTE_ZERO ((UBYTE) 0) /* Description: Numerical constant 0. */

#define VALLEY ((Bool) 0)
#define FLOAT_ONE_HUNDRED_EIGHTY ((Float32) 180.F) /* Description: Numerical constant 180. */
#define FLOAT_ONE_HUNDRED_FIFTY ((Float32) 150.F) /* Description: Numerical constant 150. */
#define FLOAT_POINT_THREE ((Float32) 0.3F) /* Description: Numerical constant 0.3. */
#define FLOAT_POINT_FOUR ((Float32) 0.4F) /* Description: Numerical constant 0.4. */
#define FLOAT_THREE_HUNDRED ((Float32) 300.F) /* Description: Numerical constant 300. */
#define FLOAT_THREE_HUNDRED_SIXTY ((Float32) 360.F) /* Description: Numerical constant 360. */

#define FLOAT_INV_FOUR_HUNDRED_FORTY ((Float32) 0.002272727F) /* Description: Numerical constant 1/440. */
#define FLOAT_INV_TWO_HUNDRED_TWENTY ((Float32) 0.0045454545F) /* Description: Numerical constant 1/220. */

/*--------------------------------------------------------------------------------------------------------------------------------------------------*\
  TYPEDEFS
 \*--------------------------------------------------------------------------------------------------------------------------------------------------*/
/*--------------------------------------------------------------------------------------------------------------------------------------------------*\
  VARIABLES
 \*--------------------------------------------------------------------------------------------------------------------------------------------------*/
/*--------------------------------------------------------------------------------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
 \*--------------------------------------------------------------------------------------------------------------------------------------------------*/
/*--------------------------------------------------------------------------------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
 \*--------------------------------------------------------------------------------------------------------------------------------------------------*/
#endif /* EXTERN_MACRO_C2000_H */
/*--------------------------------------------------------------------------------------------------------------------------------------------------*\
  END OF FILE
 \*--------------------------------------------------------------------------------------------------------------------------------------------------*/
